### ISSUE TITLE
drop notice?

### ISSUE THREAD

**Issue by srenatus** [infracost/setup-opa#4]
I've just noticed (haha) that `core.notice` (https://github.com/infracost/setup-opa/blob/master/src/index.ts#L131) causes a build annotation like this:

![image](https://user-images.githubusercontent.com/870638/149206890-9ae27810-6c71-469b-ac80-3fbf593bd837.png)

I think we'd better use those more sparingly, i.e. drop that line. What do you think?

**Comment by alikhajeh1** [comment]
@srenatus I hadn't noticed that before either! Do you have a link to an example PR that shows this? I googled a bit for github annotations but couldn't find an example to see how it looks

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/actions/runs/1691836944 Any recent OPA PR, really 😄 We've started using it there.

**Comment by srenatus** [comment]
It also looks like something's worrying here:

![image](https://user-images.githubusercontent.com/870638/149304926-9fc63fc8-57c2-42ce-a1e0-dc231a06335a.png)

https://github.com/open-policy-agent/opa/pull/4221/checks

**Comment by alikhajeh1** [comment]
Thanks! Yeah I think just logging the version in the [console output](https://github.com/open-policy-agent/opa/runs/4800819678?check_suite_focus=true#step:3:1) is better than an annotation. @tim775 can you possibly do the same for the infracost/setup action?
